# Change paths here (optional)
data_dir: data
out_dir: results
images_dir: images

# Change names here
name_in_img: qr_code.png
name_out_img: qr_code_picturized.png
replace_color: "bright" # dark or bright
width: 1200 # resulting image width

# Ignore this
hydra:
  output_subdir: null
  run:
    dir: .
