# Change parameters here

# name of existing code - use -pic flag
name_in_img: qr_code.png

# name of the generated qr code
name_gen_qr: test_qr_code.png

# name of picturized qr code
name_out_img: qr_picturized.png

# maximal width of resulting image
width: 1200

# replace bright (white) or dark (black) colors in qr code?
replace_color: "dark"
